### ISSUE TITLE
Getting error while using  rails generate has_friendship

### ISSUE THREAD

**Issue by setshaft** [sungwoncho/has_friendship#8]
```
siddhardha@sidddhardha:~/billpin$ rails generate has_friendship
/home/siddhardha/.rvm/gems/ruby-2.2.0/gems/orm_adapter-0.5.0/lib/orm_adapter/adapters/active_record.rb:81: warning: already initialized constant ActiveRecord::Base::OrmAdapter
/home/siddhardha/.rvm/gems/ruby-2.2.0/gems/orm_adapter-0.5.0/lib/orm_adapter/adapters/active_record.rb:81: warning: previous definition of OrmAdapter was here
/home/siddhardha/.rvm/gems/ruby-2.2.0/gems/orm_adapter-0.5.0/lib/orm_adapter/adapters/active_record.rb:81: warning: already initialized constant ActiveRecord::Base::OrmAdapter
/home/siddhardha/.rvm/gems/ruby-2.2.0/gems/orm_adapter-0.5.0/lib/orm_adapter/adapters/active_record.rb:81: warning: previous definition of OrmAdapter was here
/home/siddhardha/.rvm/gems/ruby-2.2.0/gems/activerecord-4.1.8/lib/active_record/dynamic_matchers.rb:26:in `method_missing': undefined method `raise_in_transactional_callbacks=' for #<Class:0x000000037c7448> (NoMethodError)
	from /home/siddhardha/.rvm/gems/ruby-2.2.0/gems/activerecord-4.1.8/lib/active_record/railtie.rb:110:in `block (3 levels) in <class:Railtie>'
	from /home/siddhardha/.rvm/gems/ruby-2.2.0/gems/activerecord-4.1.8/lib/active_record/railtie.rb:109:in `each'
	from /home/siddhardha/.rvm/gems/ruby-2.2.0/gems/activerecord-4.1.8/lib/active_record/railtie.rb:109:in `block (2 levels) in <class:Railtie>'
	from /home/siddhardha/.rvm/gems/ruby-2.2.0/gems/activesupport-4.1.8/lib/active_support/lazy_load_hooks.rb:38:in `instance_eval'
	from /home/siddhardha/.rvm/gems/ruby-2.2.0/gems/activesupport-4.1.8/lib/active_support/lazy_load_hooks.rb:38:in `execute_hook'
	from /home/siddhardha/.rvm/gems/ruby-2.2.0/gems/activesupport-4.1.8/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
	from /home/siddhardha/.rvm/gems/ruby-2.2.0/gems/activesupport-4.1.8/lib/active_support/lazy_load_hooks.rb:44:in `each'
	from /home/siddhardha/.rvm/gems/ruby-2.2.0/gems/activesupport-4.1.8/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
	from /home/siddhardha/.rvm/gems/ruby-2.2.0/gems/activerecord-4.1.8/lib/active_record/base.rb:326:in `<module:ActiveRecord>'
	from /home/siddhardha/.rvm/gems/ruby-2.2.0/gems/activerecord-4.1.8/lib/active_record/base.rb:23:in `<top (required)>'
	from /home/siddhardha/.rvm/gems/ruby-2.2.0/gems/devise-3.5.2/lib/devise/orm/active_record.rb:3:in `<top (required)>'
	from /home/siddhardha/.rvm/gems/ruby-2.2.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:247:in `require'
	from /home/siddhardha/.rvm/gems/ruby-2.2.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:247:in `block in require'
	from /home/siddhardha/.rvm/gems/ruby-2.2.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:232:in `load_dependency'
	from /home/siddhardha/.rvm/gems/ruby-2.2.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:247:in `require'
	from /home/siddhardha/billpin/config/initializers/devise.rb:24:in `block in <top (required)>'
	from /home/siddhardha/.rvm/gems/ruby-2.2.0/gems/devise-3.5.2/lib/devise.rb:278:in `setup'
	from /home/siddhardha/billpin/config/initializers/devise.rb:3:in `<top (required)>'
	from /home/siddhardha/.rvm/gems/ruby-2.2.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:241:in `load'
	from /home/siddhardha/.rvm/gems/ruby-2.2.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:241:in `block in load'
	from /home/siddhardha/.rvm/gems/ruby-2.2.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:232:in `load_dependency'
	from /home/siddhardha/.rvm/gems/ruby-2.2.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:241:in `load'
	from /home/siddhardha/.rvm/gems/ruby-2.2.0/gems/railties-4.1.8/lib/rails/engine.rb:648:in `block in load_config_initializer'
	from /home/siddhardha/.rvm/gems/ruby-2.2.0/gems/activesupport-4.1.8/lib/active_support/notifications.rb:161:in `instrument'
	from /home/siddhardha/.rvm/gems/ruby-2.2.0/gems/railties-4.1.8/lib/rails/engine.rb:647:in `load_config_initializer'
	from /home/siddhardha/.rvm/gems/ruby-2.2.0/gems/railties-4.1.8/lib/rails/engine.rb:612:in `block (2 levels) in <class:Engine>'
	from /home/siddhardha/.rvm/gems/ruby-2.2.0/gems/railties-4.1.8/lib/rails/engine.rb:611:in `each'
	from /home/siddhardha/.rvm/gems/ruby-2.2.0/gems/railties-4.1.8/lib/rails/engine.rb:611:in `block in <class:Engine>'
	from /home/siddhardha/.rvm/gems/ruby-2.2.0/gems/railties-4.1.8/lib/rails/initializable.rb:30:in `instance_exec'
	from /home/siddhardha/.rvm/gems/ruby-2.2.0/gems/railties-4.1.8/lib/rails/initializable.rb:30:in `run'
	from /home/siddhardha/.rvm/gems/ruby-2.2.0/gems/railties-4.1.8/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /home/siddhardha/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
	from /home/siddhardha/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
	from /home/siddhardha/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:420:in `block (2 levels) in each_strongly_connected_component_from'
	from /home/siddhardha/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
	from /home/siddhardha/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:419:in `block in each_strongly_connected_component_from'
	from /home/siddhardha/.rvm/gems/ruby-2.2.0/gems/railties-4.1.8/lib/rails/initializable.rb:44:in `each'
	from /home/siddhardha/.rvm/gems/ruby-2.2.0/gems/railties-4.1.8/lib/rails/initializable.rb:44:in `tsort_each_child'
	from /home/siddhardha/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:413:in `call'
	from /home/siddhardha/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:413:in `each_strongly_connected_component_from'
	from /home/siddhardha/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
	from /home/siddhardha/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:345:in `each'
	from /home/siddhardha/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:345:in `call'
	from /home/siddhardha/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
	from /home/siddhardha/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
	from /home/siddhardha/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
	from /home/siddhardha/.rvm/gems/ruby-2.2.0/gems/railties-4.1.8/lib/rails/initializable.rb:54:in `run_initializers'
	from /home/siddhardha/.rvm/gems/ruby-2.2.0/gems/railties-4.1.8/lib/rails/application.rb:300:in `initialize!'
	from /home/siddhardha/billpin/config/environment.rb:5:in `<top (required)>'
	from /home/siddhardha/.rvm/gems/ruby-2.2.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:247:in `require'
	from /home/siddhardha/.rvm/gems/ruby-2.2.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:247:in `block in require'
	from /home/siddhardha/.rvm/gems/ruby-2.2.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:232:in `load_dependency'
	from /home/siddhardha/.rvm/gems/ruby-2.2.0/gems/activesupport-4.1.8/lib/active_support/dependencies.rb:247:in `require'
	from /home/siddhardha/.rvm/gems/ruby-2.2.0/gems/spring-1.4.0/lib/spring/application.rb:92:in `preload'
	from /home/siddhardha/.rvm/gems/ruby-2.2.0/gems/spring-1.4.0/lib/spring/application.rb:143:in `serve'
	from /home/siddhardha/.rvm/gems/ruby-2.2.0/gems/spring-1.4.0/lib/spring/application.rb:131:in `block in run'
	from /home/siddhardha/.rvm/gems/ruby-2.2.0/gems/spring-1.4.0/lib/spring/application.rb:125:in `loop'
	from /home/siddhardha/.rvm/gems/ruby-2.2.0/gems/spring-1.4.0/lib/spring/application.rb:125:in `run'
	from /home/siddhardha/.rvm/gems/ruby-2.2.0/gems/spring-1.4.0/lib/spring/application/boot.rb:18:in `<top (required)>'
	from /home/siddhardha/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/siddhardha/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'
```

This is the error log.

**Comment by sungwoncho** [comment]
Can you provide versions of Rails and this gem you are using?

**Comment by setshaft** [comment]
latest version of the gem and 4.2.4 of rails


On Mon, Sep 28, 2015 at 6:35 PM, Sung Won Cho <notifications@github.com>
wrote:

> Can you provide versions of Rails and this gem you are using?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sungwoncho/has_friendship/issues/8#issuecomment-143738283>
> .
>



-- 
Regards,
Siddhardha Tagirisa,
Computer Science and Engineerig
N.I.T.,Rourkela.
Reach me at +91 9703040028.

**Comment by sungwoncho** [comment]
What are the steps to reproduce?

**Comment by sungwoncho** [comment]
Please re-open with instructions of how to reproduce.
